### ISSUE TITLE
XSS Vulnerabilities

### ISSUE THREAD

**Issue by josdejong** [NoMoreDeps/marks-lite-te#1]
This template engine is not secure against XSS attacks. It does not protect against injecting malicious JavaScript in either the context values or the template itself. 

Given the example from the README:

```js
import { liteTE } from "@marks-js/lte";

// Here you can specify data to use inside the template
const context = {
  title: "Hello Kitty",
  items: [
    "Item 01",
    "Item 02",
    "Item 03",
    "Item 04"
  ]
};

// Use {% javascript statement %}
// {%= javascript result of any value or expression %}
// {% LF %} use LF to add a linefeed or "\\n"

// The template source
const source = `
<h1>Here is the title : {%= this.title %}</h1>

<ol>{% for(let itm of this.items) { %}
  <li>{%= itm %}</li>{% } %}
</ol>
`;

const output = liteTE(source, context);

console.log(output);
``` 

When I change the context to:

```js
const context = {
  title: "Hello Kitty",
  items: [
    "Item 01",
    "Item 02",
    "Item 03",
    "Item 04",
    "<script>console.log('Hacked! I can execute any JavaScript I like!')</script>"
  ]
};
``` 

The generated output will become:

```html
<h1>Here is the title : Hello Kitty</h1>

<ol>
  <li>Item 01</li>
  <li>Item 02</li>
  <li>Item 03</li>
  <li>Item 04</li>
  <li><script>console.log('Hacked! I can execute any JavaScript I like!')</script></li>
</ol>
```

When I load this in a web application, the (in this case harmless) `console.log` will be executed. When these context values are loaded from arbitrary user input (maybe coming from a database), any user would be able to insert a value allowing to execute arbitrary JavaScript on the pages that loads this template.

Also, because the template engine makes use of `new Function(...)`, it in itself is also vulnerable to injecting JavaScript via a template itself, not even the values.

**Comment by NoMoreDeps** [comment]
Hi @josdejong , thank you so much for the time you have taken to provide this clear description.
I have to apology.

The readme is misleading, incomplete, and just wrong, you are right, the too lite template engine is used outside a web scope, to replace a liquid template in a static website generator, where I *exaclty* need to produce unsanitized output.

I didn't even imagine anyone will try it so soon, juste because it is javascript templating, obviously useless on the front side.

But, it is publicy accessible, so I have to ensure that by default, including in a web context, there is no easy way to inject code.

I will enable by default a check and will sanitize.

Thank you again for the feedback, I feel like a noob now 🤣

**Comment by josdejong** [comment]
> Thank you again for the feedback, I feel like a noob now 🤣

😂 I've been there. 

Also when the code is generated on the backend, it will in the end be rendered in in the frontend. So as soon as there is dynamic inputs or templates this security vulnerability is a real risk, no matter whether rendering in the frontend or backend.

**Comment by NoMoreDeps** [comment]
Ok, I started a pull request to fix what can be fixed on it. 

Even if I truly agree, the way you use it matter. 
In **absolute terms**, frontend or backend generation, same problem.

In reality, it is not as simple as that. If you use a tool like Checkmarx, the tool will deeply analyse the code the way you use it, and will raise an error regarding the fact that the **input** template code has been loaded from an arbitrary source (DB, fetch, file system) but it will not point the template engine itself.

The vulnerability will be that the code, from loading to the final result, has not been checked at all before being returned to the client.
Thus, any piece of code that will check the template will be able to stop the vulnerability.

When I use the template engine to scaffold source code files on a c# project, I don't want, either i don't need to sanitize because the output is not for rendering web stuff at all. And inside the static website generator (used in CLI), there is no arbitrary input, it is used to produce HTML the way to needs to, including script tags.

So again, I fully agree with you, just want to be sure this issue will not start an infinite debate 🤣 

If you have a point of view, comment, recommandation that can help, fell free to do so.

Thanks again @josdejong , I appreciate.

**Comment by josdejong** [comment]
👍  I'm not using `marks-lite-te` but I saw it and was triggered by the absence of any protective measures. Just wanted you to be aware of it. If we drop stuff on npm for others to use, we do have a responsibility to keep it safe in my opinion. 

It's not trivial to get such a template engine secure, and if it isn't relevant for your use case it may be a waste of time. There are quite some nice and battle tested template engines out there, so I'm not sure if `marks-lite-te` has added value over those, but that's up to you to think through 😄 .

An easy measure though is to clearly warn users that `marks-lite-te` is not secure against XSS and explain what the do's and don'ts for the library are.

**Comment by NoMoreDeps** [comment]
> If we drop stuff on npm for others to use, we do have a responsibility to keep it safe in my opinion.

I think this is the ultimate point :-)
There is absolutly no added value, it is just small enough to be easily used in several project I have.

But I will definitly add little protection and better warning as you propose.
Thanks again for all your time, it is a very good reminder about responsibility we have with public source code we provide.

**Comment by josdejong** [comment]
👍
